import 'package:flutter/material.dart';
class NormalDDDbModel{

  int id;
  String userId;
  String ddFromPage;
  String tempDDNumber;
  String ddFirstNumber;
  String ddDelayTimes;
  String createDate;
  String updateDate;
  String ddMBCode;
  String ddNumber1;
  String ddWorkNo;
  String ddPlaneNo;
  String ddEng;
  String ddFrom;
  String ddReportDate;
  String ddReportPlace;
  String ddStartDate;
  String ddStartTime2;
  String ddStartTime3;
  String ddDay;
  String ddHour;
  String ddCycle;
  String ddEndTime1;
  String ddEndTime2;
  String ddEndTime3;
  String ddKeepDescribe;
  String ddKeepMeasure;
  String ddName;
  String ddJno;
  String ddFaultNum;
  String ddInstallNum;
  String ddReleaseNum;
  String ddChapter1;
  String ddChapter2;
  String ddChapter3;
  String ddFaultCategory;
  String ddInfluence;
  int ddo;
  int ddOther;
  String ddOtherDescribe;
  int ddOI;
  int ddLS;
  int ddSG;
  int ddSP;
  String ddParkingTime;
  String ddWorkHour;
  int ddNeedM;
  int ddNeedRun;
  int ddNeedAmc;
  int ddNeedKeepToFold;
  int ddNeedKeepRepeatInspection;
  String ddEvidence;
  String ddChapterNo1;
  String ddChapterNo2;
  String ddChapterNo3;
  String ddChapterNo4;
  String ddChapterNo5;
  String ddTransferDate;
  String ddDelayDate;
  String ddApplicationDate;

  NormalDDDbModel parseDataMap(Map<String, dynamic> dataMap){
    id =dataMap['id'];
    userId=dataMap['userId'];
    ddFromPage=dataMap['dd_from_page'];//来自，新增，任务新增，临保转办，dd转办，dd延期；
    tempDDNumber=dataMap['temp_dd_number'];//临保转办时的临保编号；
    ddFirstNumber=dataMap['dd_first_number'];//dd转办，延期的首办号；
    ddDelayTimes=dataMap['dd_delay_times'];//dd延期次数；
    ddMBCode=dataMap['dd_MBCode'];
    ddNumber1= dataMap['dd_number1'];
    ddWorkNo=dataMap['dd_WorkNo'];
    ddPlaneNo= dataMap['dd_planeNo'];
    ddEng=dataMap['dd_ENG'];
    ddFrom=dataMap['dd_from'];
    ddReportDate= dataMap['dd_firstReportDate'];
    ddReportPlace= dataMap['dd_firstReportPlace'];
    ddStartDate=dataMap['dd_startDate'];
    ddStartTime2=dataMap['dd_start_time2'];
    ddStartTime3=dataMap['dd_start_time3'];
    ddDay=dataMap['dd_plan_keep_time1'];
    ddHour=dataMap['dd_plan_keep_time2'];
    ddCycle=dataMap['dd_plan_keep_time3'];
    ddEndTime1=dataMap['dd_end_time1'];
    ddEndTime2=dataMap['dd_end_time2'];
    ddEndTime3=dataMap['dd_end_time3'];
    ddKeepDescribe= dataMap['dd_plan_keep_describe'];
    ddKeepMeasure= dataMap['dd_keepMeasure'];
    ddName= dataMap['dd_name'];
    ddJno= dataMap['dd_jno'];
    ddFaultNum= dataMap['dd_faultNum'];
    ddInstallNum= dataMap['dd_installNum'];
    ddReleaseNum= dataMap['dd_releaseNum'];
    ddChapter1= dataMap['dd_chapter1'];
    ddChapter2= dataMap['dd_chapter2'];
    ddChapter3= dataMap['dd_chapter3'];
    ddFaultCategory= dataMap['dd_keep_faultCategory'];
    ddInfluence= dataMap['dd_influence'];
    ddo= dataMap['dd_o'];
    ddOther= dataMap['dd_other'];
    ddOtherDescribe= dataMap['dd_other_describe'];
    ddOI= dataMap['dd_oi'];
    ddLS= dataMap['dd_ls'];
    ddSG= dataMap['dd_sg'];
    ddSP= dataMap['dd_sp'];
    ddParkingTime= dataMap['dd_need_parking_time'];
    ddWorkHour= dataMap['dd_need_work_time'];
    ddNeedM= dataMap['dd_need_m'];
    ddNeedRun= dataMap['dd_need_run_limit'];
    ddNeedAmc= dataMap['dd_need_amc'];
    ddNeedKeepToFold=dataMap['dd_needKeepToFold'];
    ddNeedKeepRepeatInspection=dataMap['dd_needRepeatInspection'];
    ddEvidence= dataMap['dd_evidence_type'];
    ddChapterNo1= dataMap['dd_chapter_no1'];
    ddChapterNo2= dataMap['dd_chapter_no2'];
    ddChapterNo3= dataMap['dd_chapter_no3'];
    ddChapterNo4= dataMap['dd_chapter_no4'];
    ddChapterNo5= dataMap['dd_chapter_no5'];
    ddTransferDate= dataMap['dd_transfer_date_title'];
    ddDelayDate= dataMap['dd_delay_date_title'];
    ddApplicationDate= dataMap['dd_applicationDate'];
    return this;
  }

}